# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

"""Example C++ applications demonstrating SCORE Bazel C++ toolchain usage.

Tests have been moved to the ../tests/ directory.
See ../docs/test_suite.md for comprehensive test documentation.
"""

# This file is preserved for potential future example applications.
